routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/items', 'ItemController')->middleware('auth');
Route::resource('/distributors', 'DistributorController')->middleware('auth');
Route::resource('/factories', 'FactoryController')->middleware('auth');
Route::resource('/purchasing', 'PurchasingController')->middleware('auth');

app/Http/Controllers/PurchasingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Item;
use App\Distributor;
use App\Factory;
use App\Purchase;
use App\PurchaseDetail;

class PurchasingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $purchases = Purchase::all();
        return view('purchasing.index', compact('purchases'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $distributors = Distributor::where('aktif',1)
                        ->orderBy('nama', 'asc')
                        ->get();
        $items = Item::where('aktif',1)
                    ->orderBy('nama', 'asc')
                    ->get();
        return view('purchasing.create',["distributors" => $distributors, "items" => $items]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kode'=>'required',
            'nama'=>'required'
        ]);
        $factory = new Factory([
            'kode'          => $request->get('kode'),
            'nama'          => $request->get('nama'),
            'alamat'        => preg_replace("/\n/", "<br>", $request->get('alamat')),
            'telp_kantor'   => $request->get('telp_kantor'),
            'narahubung'    => $request->get('narahubung'),
            'telp_narahubung' => $request->get('telp_narahubung'),
            'aktif'         => $request->get('aktif')
        ]);
        $factory->save();
        return redirect('/factories')->with('success', 'Pabrik berhasil disimpan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $factory = Factory::find($id);
        return view('factories.edit', compact('factory')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kode'=>'required',
            'nama'=>'required'
        ]);

        $factory = Factory::find($id);
        $factory->kode         =  $request->get('kode');
        $factory->nama         = $request->get('nama');
        $factory->alamat  = preg_replace("/\n/", "<br>", $request->get('alamat'));
        $factory->telp_kantor         = $request->get('telp_kantor');
        $factory->narahubung        = $request->get('narahubung');
        $factory->telp_narahubung = $request->get('telp_narahubung');
        $factory->aktif        = $request->get('aktif');
        $factory->save();
        return redirect('/factories')->with('success', 'Pabrik berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $factory = Factory::find($id);
        $factory->delete();

        return redirect('/factories')->with('success', 'Factory berhasil dihapus!');
    }
}

resources/views/purchasing/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 	<div class="col-sm-6 offset-sm-1">
    	<h1 class="display-3">Tambah pembelian</h1>
  		<div>
    		@if ($errors->any())
      			<div class="alert alert-danger">
        		<ul>
            		@foreach ($errors->all() as $error)
              		<li>{{ $error }}</li>
            		@endforeach
        		</ul>
      			</div><br />
    		@endif
    	</div>
    </div>
 	<div class="col-sm-10 offset-sm-1">
 		<div>
      		<form method="post" action="{{ route('distributors.store') }}">
          		@csrf
          		<div class="form-group">    
              		<label for="nomor_masuk" class="col-sm-4">Nomor Pembelian:</label>
              		<div class="col-sm-8">
	              		<input type="text" class="form-control" name="nomor_masuk"/>
              		</div>
	          	</div>
	          	<div class="form-group">    
              		<label for="distributor_id" class="col-sm-4">Distributor:</label>
              		<div class="col-sm-8">
	              		<select class="form-control" name="distributor_id">
	              			<option value="0">- Pilih Distributor -</option>
	              			@foreach($distributors as $distributor)
								<option value="{{$distributor->id}}">{{$distributor->nama}}</option>
	              			@endforeach
	              		</select>
	              	</div>
	          	</div>
	          	<div class="form-group">    
              		<label for="nomor_faktur" class="col-sm-4">Nomor Faktur:</label>
              		<div class="col-sm-8">
              			<input type="text" class="form-control" name="nomor_faktur"/>
              		</div>
	          	</div>
	          	<div class="form-group">    
              		<label for="tanggal_faktur" class="col-sm-4">Tgl Faktur:</label>
              		<div class="col-sm-8">
	              		<input type="text" class="form-control" name="tanggal_faktur"/>
	              	</div>
	          	</div>
          		<button type="button" id="btn_add_item" class="btn btn-primary">Tambah Item</button>
	          	<div style="max-width: 100%; overflow-x: scroll;">
	          		<table class="table table-striped" id="tbl-item">
			        <thead>
			            <tr>
			                <td>No</td>
			                <td>Item</td>
			                <td>Satuan</td>
			                <td>Harga Satuan</td>
			                <td>Jumlah</td>
			                <td>Sub-Total</td>
			                <td>Diskon (%)</td>
			                <td>Diskon (Rp.)</td>
							<td>Pajak (%)</td>
							<td>Pajak (Rp.)</td>
			                <td>Harga Netto</td>
							<td>Hapus</td>
			            </tr>
			        </thead>
			        <tbody>
			        </tbody>
			    	</table>
				</div>
				<div></div>
				<div class="form-group">
	          		<button type="submit" class="btn btn-primary">Simpan Pembelian</button>&emsp;
	          		<a href="{{route('purchasing.index')}}" class="btn btn-danger">Batal</a>
	          	</div>
	     	</form>
  		</div>
	</div>
</div>
@endsection

@section('footer_scripts')
<script type="text/javascript">
	$(document).ready(function(){ 
		$('#btn_add_item').on('click', function(){
			var jmlRow = $('#tbl-item tbody tr').length + 1;
			$('#tbl-item tbody').append('<tr><td class="urut">'+jmlRow+'</td>'+
				'<td><select class="input-sm item_id" name="detail[][\'item_id\']" id="item_id_'+jmlRow+'" onchange="set_satuan($(this));">'+
	              			'<option value="0">- Pilih Item -</option>'+
	              			@foreach($items as $item)
								'<option value="{{$item->id}}||{{$item->kemasan_besar}}">{{$item->nama}} - {{$item->merk}} ({{$item->model}})</option>'+
	              			@endforeach
	              		'</select></td>'+
				'<td><input type="text" name="detail[][\'satuan\']" id="satuan_'+jmlRow+'" class="input-sm satuan" readonly="true" tabIndex="-1" /></td>'+
				'<td><input type="number" name="detail[][\'harga_satuan\']" id="harga_satuan_'+jmlRow+'" class="input-sm harga_satuan text-right" value="0" onkeyup="hitung_total($(this));" /></td>'+
				'<td><input type="number" name="detail[][\'jml_masuk\']" id="jml_masuk_'+jmlRow+'" class="input-sm jml_masuk text-right" value="0" onkeyup="hitung_total($(this));" /></td>'+
				'<td><input type="number" name="detail[][\'sub_total\']" id="sub_total_'+jmlRow+'" class="input-sm sub_total text-right" value="0" readonly="true" tabIndex="-1" /></td>'+
				'<td><input type="number" name="detail[][\'diskon_persen\']" id="diskon_persen_'+jmlRow+'" class="input-sm diskon_persen text-right" value="0" onkeyup="hitung_total($(this));" /></td>'+
				'<td><input type="number" name="detail[][\'diskon_nominal\']" id="diskon_nominal_'+jmlRow+'" class="input-sm diskon_nominal text-right" value="0" readonly="true" tabIndex="-1" /></td>'+
				'<td><input type="number" name="detail[][\'pajak\']" id="pajak_'+jmlRow+'" class="input-sm pajak text-right" value="0" onkeyup="hitung_total($(this));" /></td>'+
				'<td><input type="number" name="detail[][\'pajak_nominal\']" id="pajak_nominal_'+jmlRow+'" class="input-sm pajak_nominal text-right" value="0" readonly="true" tabIndex="-1" /></td>'+
				'<td><input type="number" name="detail[][\'harga_netto\']" id="harga_netto_'+jmlRow+'" class="input-sm harga_netto text-right" value="0" /></td>'+
				'<td><button type="button" class="btn btn-danger btn-sm" onclick="hapus($(this))">Hapus</button></td></tr>');
			$('#tbl-item tbody tr:last-child').find('.item_id').focus();
		});

	});

	function hapus(el) {
		el.closest('tr').remove();
		urut_ulang();
	}

	function urut_ulang() {
		$.each($('.urut'), function(index,value) {
			$(this).html(index+1);
		})
	}

	function set_satuan(el) {
		var value = el.val().split('||');
		el.closest('tr').find('.satuan').val(value[1]);
		el.closest('tr').find('.harga_satuan').focus();
	}

	function hitung_total(el) {
		var hargaSatuan = parseFloat(el.closest('tr').find('.harga_satuan').val());
		var jumlah 		= parseFloat(el.closest('tr').find('.jml_masuk').val());
		var diskonPersen= parseFloat(el.closest('tr').find('.diskon_persen').val());
		var pajak		= parseFloat(el.closest('tr').find('.pajak').val());
		
		var subTotal 	= hargaSatuan * jumlah;
		var	diskonNum = (subTotal * diskonPersen / 100);
		var hargaTemp 	= subTotal - diskonNum;
		var pajakNum 	= (hargaTemp * pajak / 100);
		var hargaNetto 	= hargaTemp + pajakNum;

		el.closest('tr').find('.sub_total').val(subTotal);
		el.closest('tr').find('.diskon_nominal').val(diskonNum);
		el.closest('tr').find('.pajak_nominal').val(pajakNum);
		el.closest('tr').find('.harga_netto').val(hargaNetto);

		console.log('hargaSatuan: '+hargaSatuan);
		console.log('jumlah: '+jumlah);
		console.log('diskonPersen: '+diskonPersen);
		console.log('diskonNum: '+diskonNum);
		console.log('pajak: '+pajak);
		console.log('subTotal: '+subTotal);
		console.log('hargaTemp: '+hargaTemp);
		console.log('pajakNum: '+pajakNum);
		console.log('hargaNetto: '+hargaNetto);
	}
</script>
@stop

resources/views/purchasing/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 	<div class="col-sm-6 offset-sm-2">
    	<h1 class="display-3">Ubah data distributor</h1>
  		<div>
    		@if ($errors->any())
      			<div class="alert alert-danger">
        		<ul>
            		@foreach ($errors->all() as $error)
              		<li>{{ $error }}</li>
            		@endforeach
        		</ul>
      			</div><br>
    		@endif
      		<form method="post" action="{{ route('distributors.update', $distributor->id) }}">
      			@method('PATCH')
          		@csrf
          		<div class="form-group">    
              		<label for="kode">Kode:</label>
              		<input type="text" class="form-control" name="kode" value="{{$distributor->kode}}" />
	          	</div>
	          	<div class="form-group">
	              	<label for="nama">Nama:</label>
	              	<input type="text" class="form-control" name="nama" value="{{$distributor->nama}}"/>
	         	</div>
	          	<div class="form-group">
	              	<label for="alamat">Alamat:</label>
	              	<textarea class="form-control" name="alamat" cols="30" rows="4">{{str_replace("<br>","\n",$distributor->alamat)}}</textarea>
	          	</div>
	          	<div class="form-group">
	              	<label for="telp_kantor">Telp Kantor:</label>
	              	<input type="text" class="form-control" name="telp_kantor" value="{{$distributor->telp_kantor}}"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="narahubung">Contact Person:</label>
	              	<input type="text" class="form-control" name="narahubung" value="{{$distributor->narahubung}}"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="telp_narahubung">Telp. CP.:</label>
	              	<input type="text" class="form-control" name="telp_narahubung" value="{{$distributor->telp_narahubung}}"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="aktif">Aktif:</label>
	              	<select class="form-control" name="aktif">
	              		<option value="1" {{($distributor->aktif == '1')?'selected':''}}>Aktif</option>
	              		<option value="0" {{($distributor->aktif == '0')?'selected':''}}>Non-Aktif</option>
	              	</select>
	          	</div>
	          	<button type="submit" class="btn btn-primary">Ubah Data</button>&emsp;
	          	<a href="{{route('distributors.index')}}" class="btn btn-danger">Batal</a>
	     	</form>
  		</div>
	</div>
</div>
@endsection

resources/views/purchasing/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-12">
        @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}  
        </div>
        @endif
        <div class="row">
            <div class="col-sm-8">
                <h1 class="display-3">Daftar Pembelian</h1>    
            </div>
            <div class="col-sm-4">
                <a href="{{ route('purchasing.create')}}" class="btn btn-primary"></i>Tambah</a>
            </div>
        </div>
        <table class="table table-striped">
        <thead>
            <tr>
                <td>No</td>
                <td>Tgl Beli</td>
                <td>Nomor Pembelian</td>
                <td>Distributor</td>
                <td>Nomor Faktur</td>
                <td>Tanggal Faktur</td>
                <td>Total</td>
                <td colspan = 2>Actions</td>
            </tr>
        </thead>
        <tbody>
            @foreach($purchases as $key => $purchasing)
            <tr>
                <td>{{$key+1}}</td>
                <td>{{date('d-m-Y', strtotime($purchasing->created_at))}}</td>
                <td>{{ $purchasing->nomor_masuk }}</td>
                <td>{{$purchasing->distributor_nama}}</td>
                <td>{{$purchasing->nomor_faktur}}</td>
                <td>{{date('d-m-Y', strtotime($purchasing->tanggal_faktur))}}</td>
                <td>{{ number_format($purchasing->aktif, 2, ',', '.') }}</td>
                <td>
                    <a href="{{ route('purchasing.edit',$purchasing->id)}}" class="btn btn-primary">Edit</a>
                </td>
                <td>
                    <form action="{{ route('purchasing.destroy', $purchasing->id)}}" method="post">
                      @csrf
                      @method('DELETE')
                      <button class="btn btn-danger" type="submit" onclick="if(confirm('Lanjutkan hapus data?')) {return true;} else {return false;}">Hapus</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
        </table>
    <div>
</div>
@endsection