routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/items', 'ItemController')->middleware('auth');
Route::resource('/distributors', 'DistributorController')->middleware('auth');
Route::resource('/factories', 'FactoryController')->middleware('auth');
Route::resource('/purchasing', 'PurchasingController')->middleware('auth');

app/Factory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Factory extends Model
{
    protected $fillable = [
    		"kode",
			"nama",
			"alamat",
			"telp_kantor",
			"narahubung",
			"telp_narahubung",
			"aktif"];

	public function purchase_details()
	{
		return $this->belongsTo('PurchaseDetail', 'factory_id');
	}
}

app/Http/Controllers/FactoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Factory;

class FactoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $factories = Factory::all();
        return view('factories.index', compact('factories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('factories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kode'=>'required',
            'nama'=>'required'
        ]);
        $factory = new Factory([
            'kode'          => $request->get('kode'),
            'nama'          => $request->get('nama'),
            'alamat'        => preg_replace("/\n/", "<br>", $request->get('alamat')),
            'telp_kantor'   => $request->get('telp_kantor'),
            'narahubung'    => $request->get('narahubung'),
            'telp_narahubung' => $request->get('telp_narahubung'),
            'aktif'         => $request->get('aktif')
        ]);
        $factory->save();
        return redirect('/factories')->with('success', 'Pabrik berhasil disimpan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $factory = Factory::find($id);
        return view('factories.edit', compact('factory')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kode'=>'required',
            'nama'=>'required'
        ]);

        $factory = Factory::find($id);
        $factory->kode         =  $request->get('kode');
        $factory->nama         = $request->get('nama');
        $factory->alamat  = preg_replace("/\n/", "<br>", $request->get('alamat'));
        $factory->telp_kantor         = $request->get('telp_kantor');
        $factory->narahubung        = $request->get('narahubung');
        $factory->telp_narahubung = $request->get('telp_narahubung');
        $factory->aktif        = $request->get('aktif');
        $factory->save();
        return redirect('/factories')->with('success', 'Pabrik berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $factory = Factory::find($id);
        $factory->delete();

        return redirect('/factories')->with('success', 'Pabrik berhasil dihapus!');
    }
}

resources/views/factories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 	<div class="col-sm-6 offset-sm-2">
    	<h1 class="display-3">Tambah pabrik</h1>
  		<div>
    		@if ($errors->any())
      			<div class="alert alert-danger">
        		<ul>
            		@foreach ($errors->all() as $error)
              		<li>{{ $error }}</li>
            		@endforeach
        		</ul>
      			</div><br />
    		@endif
      		<form method="post" action="{{ route('factories.store') }}">
          		@csrf
          		<div class="form-group">    
              		<label for="kode">Kode:</label>
              		<input type="text" class="form-control" name="kode"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="nama">Nama:</label>
	              	<input type="text" class="form-control" name="nama"/>
	         	</div>
	          	<div class="form-group">
	              	<label for="alamat">Alamat:</label>
	              	<textarea class="form-control" name="alamat" cols="30" rows="4"></textarea>
	          	</div>
	          	<div class="form-group">
	              	<label for="telp_kantor">Telp. Kantor:</label>
	              	<input type="text" class="form-control" name="telp_kantor"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="narahubung">Contact Person:</label>
	              	<input type="text" class="form-control" name="narahubung"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="telp_narahubung">Telp. CP.:</label>
	              	<input type="text" class="form-control" name="telp_narahubung"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="aktif">Aktif:</label>
	              	<select class="form-control" name="aktif">
	              		<option value="1">Aktif</option>
	              		<option value="0">Non-Aktif</option>
	              	</select>
	          	</div>
	          	<button type="submit" class="btn btn-primary">Simpan Pabrik</button>&emsp;
	          	<a href="{{route('factories.index')}}" class="btn btn-danger">Batal</a>
	     	</form>
  		</div>
	</div>
</div>
@endsection

resources/views/factories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 	<div class="col-sm-6 offset-sm-2">
    	<h1 class="display-3">Ubah data pabrik</h1>
  		<div>
    		@if ($errors->any())
      			<div class="alert alert-danger">
        		<ul>
            		@foreach ($errors->all() as $error)
              		<li>{{ $error }}</li>
            		@endforeach
        		</ul>
      			</div><br>
    		@endif
      		<form method="post" action="{{ route('factories.update', $factory->id) }}">
      			@method('PATCH')
          		@csrf
          		<div class="form-group">    
              		<label for="kode">Kode:</label>
              		<input type="text" class="form-control" name="kode" value="{{$factory->kode}}" />
	          	</div>
	          	<div class="form-group">
	              	<label for="nama">Nama:</label>
	              	<input type="text" class="form-control" name="nama" value="{{$factory->nama}}"/>
	         	</div>
	          	<div class="form-group">
	              	<label for="alamat">Alamat:</label>
	              	<textarea class="form-control" name="alamat" cols="30" rows="4">{{str_replace("<br>","\n",$factory->alamat)}}</textarea>
	          	</div>
	          	<div class="form-group">
	              	<label for="telp_kantor">Telp Kantor:</label>
	              	<input type="text" class="form-control" name="telp_kantor" value="{{$factory->telp_kantor}}"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="narahubung">Contact Person:</label>
	              	<input type="text" class="form-control" name="narahubung" value="{{$factory->narahubung}}"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="telp_narahubung">Telp. CP.:</label>
	              	<input type="text" class="form-control" name="telp_narahubung" value="{{$factory->telp_narahubung}}"/>
	          	</div>
	          	<div class="form-group">
	              	<label for="aktif">Aktif:</label>
	              	<select class="form-control" name="aktif">
	              		<option value="1" {{($factory->aktif == '1')?'selected':''}}>Aktif</option>
	              		<option value="0" {{($factory->aktif == '0')?'selected':''}}>Non-Aktif</option>
	              	</select>
	          	</div>
	          	<button type="submit" class="btn btn-primary">Ubah Data</button>&emsp;
	          	<a href="{{route('factories.index')}}" class="btn btn-danger">Batal</a>
	     	</form>
  		</div>
	</div>
</div>
@endsection

resources/views/factories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-12">
        @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}  
        </div>
        @endif
        <div class="row">
            <div class="col-sm-8">
                <h1 class="display-3">Daftar Pabrik</h1>    
            </div>
            <div class="col-sm-4">
                <a href="{{ route('factories.create')}}" class="btn btn-primary"></i>Tambah</a>
            </div>
        </div>
        <table class="table table-striped">
        <thead>
            <tr>
                <td>Kode</td>
                <td>Nama</td>
                <td>Alamat</td>
                <td>Telp. Kantor</td>
                <td>Contact Person</td>
                <td>Telp. CP.</td>
                <td>Status</td>
                <td colspan = 2>Actions</td>
            </tr>
        </thead>
        <tbody>
            @foreach($factories as $factory)
            <tr>
                <td>{{$factory->kode}}</td>
                <td>{{$factory->nama}}</td>
                <td>{!! $factory->alamat !!}</td>
                <td>{{$factory->telp_kantor}}</td>
                <td>{{$factory->narahubung}}</td>
                <td>{{$factory->telp_narahubung}}</td>
                <td>{{($factory->aktif == '1')?"Aktif":"Non-Aktif"}}</td>
                <td>
                    <a href="{{ route('factories.edit',$factory->id)}}" class="btn btn-primary">Edit</a>
                </td>
                <td>
                    <form action="{{ route('factories.destroy', $factory->id)}}" method="post">
                      @csrf
                      @method('DELETE')
                      <button class="btn btn-danger" type="submit" onclick="if(confirm('Lanjutkan hapus data?')) {return true;} else {return false;}">Hapus</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
        </table>
    <div>
</div>
@endsection